### ISSUE TITLE
count property for mutex

### ISSUE THREAD

**Issue by aryajur** [luarocks/argparse#17]
I could not find a way to make sure that at least one option/argument in a mutex is specified. Is there one?

**Comment by p-ouellette** [comment]
There isn't such an option, but you could do
```lua
local parser = argparse()
parser:mutex(
   parser:flag "--foo",
   parser:argument "bar":args "?"
)
local args = parser:parse()
if not (args.foo or args.bar) then
   parser:error("either '--foo' or 'bar' is required")
end
```
If the mutex only contains options it might make more sense to use a command since options are usually optional.

**Comment by aryajur** [comment]
got it!
