### ISSUE TITLE
Show help when no commands are given.

### ISSUE THREAD

**Issue by dschaper** [luarocks/argparse#20]
Is there a way to show the help by default when the script is called with just it's bare name?

The commands examples use `git` as a model and if you type `git` by itself then you see the help. I'm new to `lua` so this may be something that can be done programmatically but I've not come across any information on how to do that.

Thanks!

**Comment by daurnimator** [comment]
If you make your script require arguments (https://argparse.readthedocs.io/en/stable/arguments.html) then help will be displayed automatically if nothing matches.

myscript.lua:
```lua
#!/usr/bin/env lua

local p = require "argparse"()
p:argument("input")
p:parse()
```

Output:

```
Usage: ./myscript.lua [-h] <input>

Error: missing argument 'input'
```

**Comment by p-ouellette** [comment]
To show the full help text you can do
```lua
if not args.command then
   print(parser:get_help())
   os.exit(0)
end
```
after calling `parser:parse()`

**Comment by dschaper** [comment]
Thanks for the tips and the help!
