### ISSUE TITLE
Optional Argument with Default Value Doesn't Work

### ISSUE THREAD

**Issue by MikuAuahDark** [luarocks/argparse#22]
Here's a code example:
```lua
local argparse = require("argparse")
local parser = argparse("script", "Just test")
parser:argument("input", "Input file") -- required
parser:argument("output", "Output file", "."):args("?") -- optional
local args = select(2, assert(parser:pparse(arg)))

print(args.output)
```

Invocation of `luajit script.lua --help`
```
Usage: script [-h] <input> [<output>]

Just test

Arguments:
   input                 Input file
   output                Output file (default: .)

Options:
   -h, --help            Show this help message and exit.
```

Invocation of `luajit script.lua inputfile outputfile`:
```
outputfile
```

Invocation of `luajit script.lua inputfile`:
```
nil
```

I was expecting it to print "." (dot) but I'm getting nil instead. Is this intended behavior for argument with default value or is optional argument with default value is not a supported scenario?

**Comment by p-ouellette** [comment]
If you make the output argument required you'll get what you want. The default is ignored if the argument is allowed to consume nothing.

**Comment by MikuAuahDark** [comment]
Oh so removing `:args("?")` did the trick, thanks.
