### ISSUE TITLE
White space between option and value isn't ignored

### ISSUE THREAD

**Issue by roddypratt** [luarocks/argparse#23]
According to [the tutorial](https://argparse.readthedocs.io/en/stable/options.html) these lines are identical.

```
$ lua script.lua -f there
$ lua script.lua -fthere

{
   from = "there"
}
```
However, they aren't. The space between `f` and `there` is returned in the result.
```
local parser = argparse("MyApp")
parser:option("-f --from")
local args = {"-f there"}

local success, result = parser:pparse(args)
print (success, "'" .. result.from .. "'")
```
Gives:
`true	' there'`

**Comment by p-ouellette** [comment]
Your example has a single argument so it's equivalent to `lua script.lua "-f there"` or `lua script.lua -f" there"`.
`local args = {"-f", "there"}` will do what you expect.

**Comment by roddypratt** [comment]
Thanks. I'd forgotten that the job of splitting the command line into argv[] is done by the shell, not argparse.
